name: amdirt
channels:
  - conda-forge
dependencies:
  - click=8.0.*
  - jsonschema=4.4.0
  - numpy=1.22.3
  - pandas=1.4.2
  - pip=22.0.4
  - python
  - recommonmark=0.7.1
  - requests=2.27.1
  - rich=12.2.0
  - setuptools=62.0.0
  - sphinx=4.5.0
  - sphinx-click=3.1.0
  - sphinx_rtd_theme=1.0.0
  - streamlit>=1.12.2
  - watchdog=2.1.7
  - pyarrow
  - tox
  - pip:
    - python-dotenv==0.19.2
    - simplejson==3.17.6
    - streamlit-aggrid==0.3.3
    - protobuf==3.20.*