{% set setup_data = load_setup_py_data() %}
package:
  name: pydamage
  version: {{ setup_data['version'] }}

source:
  git_rev: {{ setup_data['version'] }}
  git_url: https://github.com/SPAAM-community/AMDirT.git

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - click=8.0.*
    - jsonschema=4.4.0
    - numpy=1.22.3
    - pandas=1.4.2
    - pip=22.0.4
    - python=3.10.4
    - recommonmark=0.7.1
    - requests=2.27.1
    - rich=12.2.0
    - setuptools=62.0.0
    - sphinx=4.5.0
    - sphinx-click=3.1.0
    - sphinx_rtd_theme=1.0.0
    - streamlit=1.8.0
    - watchdog=2.1.7
    - xmltodict=0.12.0
    - pip:
      - streamlit-aggrid==0.2.3.post2

    
test:
  commands:
    - pydamage --help

about:
  home: https://github.com/SPAAM-community/AMDirT
  license: GPL-3.0
  summary: 'AMDirT: AncientMetagenomeDir Toolkit'

# Build using: conda build .