name: amdirt

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Display action metadata
      run: |
        echo github.repository: ${{ github.repository }}
        echo github.repository_owner: ${{ github.repository_owner }}
        echo github.event_name: ${{ github.event_name }}
        echo github.workspace: ${{ github.workspace }}
        echo github.action_repository: ${{github.action_repository}}
        echo github.env: ${{ github.env }}
        echo github.workflow: ${{ github.workflow }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts
        path: /home/runner/work